"""Gemini wrapper tuned for low-latency VN <-> KR interpreting.

Latency notes (measured against the live API from this backend):

* ``thinking_budget=0`` is the single biggest win — it cuts p50 for
  ``gemini-2.5-flash`` from ~2.8s to ~1.0s and prevents the reasoning tokens
  from eating the ``max_output_tokens`` budget (which silently truncated
  answers before).
* Asking for JSON with a romanization field roughly doubles the output token
  count: plain-text streaming finishes in ~570ms where the JSON variant needs
  ~1.15s. Romanization is therefore computed locally in the browser
  (``frontend/src/romanize.ts``) instead of being generated by the model.
* Streaming plain text puts the first characters on screen at ~280ms.

The public surface is async so FastAPI can stream deltas straight to the
client without occupying a worker thread.
"""

from __future__ import annotations

import asyncio
import logging
import re
from collections.abc import AsyncIterator, Sequence
from dataclasses import dataclass
from functools import lru_cache

from google import genai
from google.genai import types

logger = logging.getLogger(__name__)

# Models that reject ``thinking_budget=0`` with 400 INVALID_ARGUMENT. Populated
# at runtime the first time a model refuses, so we only pay the failed call once
# per process instead of hardcoding a list that will drift.
_NO_ZERO_THINKING: set[str] = set()

MAX_OUTPUT_TOKENS = 1024


class TranslationError(RuntimeError):
    """Raised when Gemini fails to return a usable translation."""


@dataclass(frozen=True)
class Turn:
    """One previously translated utterance, used as conversational context."""

    source_text: str
    target_text: str


@dataclass
class TranslationResult:
    translation: str
    note: str | None = None


_TRANSLATE_SYSTEM = (
    "You are a simultaneous interpreter between Vietnamese and Korean. "
    "Output ONLY the translation, as a single line of plain text in the target "
    "language. Never repeat the source text, never add quotes, labels, "
    "romanization, explanations, alternatives or emoji. Translate the way a "
    "fluent native speaker would actually say it, not word for word: keep the "
    "speaker's intent, register and politeness level. Resolve pronouns and "
    "elided subjects using the recent conversation when it is provided. If the "
    "input is a single word or a fragment, translate just that fragment. If it "
    "is ambiguous, choose the reading that fits the stated context."
)

_STYLE_GUIDANCE = {
    "casual": (
        "Register: everyday spoken language. For Korean use the polite "
        "informal -\uc694 form (haeyo-che)."
    ),
    "formal": (
        "Register: professional business speech. For Korean use deferential "
        "-\uc2b5\ub2c8\ub2e4 / -\uc2ed\uc2dc\uc624 forms (hapsyo-che) and appropriate honorifics "
        "for a client or a senior colleague. For Vietnamese use polite "
        "\u1ea1/v\u00e2ng-level phrasing without being stiff."
    ),
}

_NOTE_SYSTEM = (
    "You explain translation choices to a Vietnamese business traveller. "
    "Answer in Vietnamese, at most two short sentences, covering only what is "
    "genuinely useful: honorific level, a cultural nuance, or an ambiguity in "
    "the source. If nothing is worth mentioning, reply with exactly: -"
)

_BACK_TRANSLATE_SYSTEM = (
    "You are a translation reviewer. Translate the given text back to the "
    "original language literally, preserving every detail so a reader can spot "
    "meaning drift. Output only the back-translation as plain text."
)


@lru_cache(maxsize=8)
def _client(api_key: str) -> genai.Client:
    """One client per API key.

    The SDK client owns the HTTP connection pool, so reusing it keeps the TLS
    session warm — rebuilding it per request added a full handshake to every
    translation.
    """
    return genai.Client(api_key=api_key)


class GeminiTranslator:
    """Low-latency Gemini-backed interpreter."""

    def __init__(self, api_key: str, model: str) -> None:
        self._client = _client(api_key)
        self._model = model

    @property
    def model(self) -> str:
        return self._model

    def _config(
        self,
        *,
        system_instruction: str,
        max_output_tokens: int = MAX_OUTPUT_TOKENS,
        allow_thinking: bool = False,
    ) -> types.GenerateContentConfig:
        thinking = None
        if not allow_thinking and self._model not in _NO_ZERO_THINKING:
            thinking = types.ThinkingConfig(thinking_budget=0)
        return types.GenerateContentConfig(
            system_instruction=system_instruction,
            temperature=0.0,
            max_output_tokens=max_output_tokens,
            thinking_config=thinking,
        )

    async def translate_stream(
        self,
        *,
        text: str,
        source: str,
        target: str,
        style: str = "casual",
        context: str | None = None,
        glossary: str | None = None,
        history: Sequence[Turn] = (),
    ) -> AsyncIterator[str]:
        """Yield translation deltas as they arrive."""
        prompt = _build_prompt(
            text=text,
            source=source,
            target=target,
            style=style,
            context=context,
            glossary=glossary,
            history=history,
        )
        async for delta in self._stream(prompt, _TRANSLATE_SYSTEM):
            yield delta

    async def translate(
        self,
        *,
        text: str,
        source: str,
        target: str,
        style: str = "casual",
        context: str | None = None,
        glossary: str | None = None,
        history: Sequence[Turn] = (),
    ) -> TranslationResult:
        chunks: list[str] = []
        async for delta in self.translate_stream(
            text=text,
            source=source,
            target=target,
            style=style,
            context=context,
            glossary=glossary,
            history=history,
        ):
            chunks.append(delta)
        translation = clean_translation("".join(chunks), source_text=text)
        if not translation:
            raise TranslationError("Gemini returned an empty translation")
        return TranslationResult(translation=translation)

    async def explain(
        self,
        *,
        text: str,
        translation: str,
        source: str,
        target: str,
    ) -> str | None:
        prompt = (
            f"Source ({source}): {text}\n"
            f"Translation ({target}): {translation}\n\n"
            "What should the Vietnamese speaker know about this translation?"
        )
        note = await self._collect(prompt, _NOTE_SYSTEM, max_output_tokens=256)
        note = note.strip().strip("-").strip()
        return note or None

    async def back_translate(self, *, translation: str, source: str, target: str) -> str:
        prompt = f"Text ({target}):\n{translation}\n\nBack-translate into {source}."
        result = await self._collect(prompt, _BACK_TRANSLATE_SYSTEM, max_output_tokens=512)
        return clean_translation(result, source_text=translation)

    async def warm_up(self) -> None:
        """Establish the TLS/HTTP2 connection so the first real call is fast."""
        try:
            await self._collect("hi", "Reply with: ok", max_output_tokens=8)
        except TranslationError as exc:
            logger.info("Gemini warm-up skipped: %s", exc)

    async def _collect(
        self,
        prompt: str,
        system_instruction: str,
        *,
        max_output_tokens: int = MAX_OUTPUT_TOKENS,
    ) -> str:
        parts: list[str] = []
        async for delta in self._stream(
            prompt, system_instruction, max_output_tokens=max_output_tokens
        ):
            parts.append(delta)
        return "".join(parts)

    async def _stream(
        self,
        prompt: str,
        system_instruction: str,
        *,
        max_output_tokens: int = MAX_OUTPUT_TOKENS,
    ) -> AsyncIterator[str]:
        try:
            async for delta in self._raw_stream(
                prompt,
                system_instruction,
                max_output_tokens=max_output_tokens,
                allow_thinking=False,
            ):
                yield delta
        except _ThinkingRejected:
            _NO_ZERO_THINKING.add(self._model)
            logger.info("Model %s rejects thinking_budget=0; retrying", self._model)
            async for delta in self._raw_stream(
                prompt,
                system_instruction,
                max_output_tokens=max_output_tokens,
                allow_thinking=True,
            ):
                yield delta

    async def _raw_stream(
        self,
        prompt: str,
        system_instruction: str,
        *,
        max_output_tokens: int,
        allow_thinking: bool,
    ) -> AsyncIterator[str]:
        config = self._config(
            system_instruction=system_instruction,
            max_output_tokens=max_output_tokens,
            allow_thinking=allow_thinking,
        )
        try:
            stream = await self._client.aio.models.generate_content_stream(
                model=self._model,
                contents=prompt,
                config=config,
            )
        except Exception as exc:  # noqa: BLE001 — normalise every SDK failure
            if not allow_thinking and _is_thinking_rejection(exc):
                raise _ThinkingRejected from exc
            raise TranslationError(_describe(exc)) from exc

        started = False
        try:
            async for chunk in stream:
                delta = chunk.text
                if not delta:
                    continue
                started = True
                yield delta
        except asyncio.CancelledError:
            raise
        except Exception as exc:  # noqa: BLE001
            if not started and not allow_thinking and _is_thinking_rejection(exc):
                raise _ThinkingRejected from exc
            raise TranslationError(_describe(exc)) from exc


class _ThinkingRejected(Exception):
    """Internal signal: the model refused ``thinking_budget=0``."""


def _is_thinking_rejection(exc: Exception) -> bool:
    message = str(exc).lower()
    return "invalid_argument" in message or "invalid argument" in message


_RETRY_DELAY_RE = re.compile(r"'retryDelay':\s*'(\d+)s'")


def _describe(exc: Exception) -> str:
    """Turn an SDK exception into something the UI can show to a traveller."""
    message = str(exc).strip() or type(exc).__name__

    # The free tier allows only ~20 requests/day/model, so quota exhaustion is
    # the failure a real user is most likely to hit. The raw SDK message is a
    # wall of JSON; say what to do instead.
    if "RESOURCE_EXHAUSTED" in message or "429" in message:
        retry = _RETRY_DELAY_RE.search(message)
        wait = f" Thử lại sau ~{retry.group(1)}s." if retry else ""
        return (
            "Hết hạn mức Gemini cho model này (gói free giới hạn rất thấp)."
            f"{wait} Đổi sang model khác hoặc bật thanh toán cho API key."
        )
    if "PERMISSION_DENIED" in message or "API_KEY_INVALID" in message:
        return "Gemini từ chối API key (sai key, chưa bật Gemini API, hoặc chặn theo vùng)."
    if "NOT_FOUND" in message or "404" in message:
        return "Model này không khả dụng với API key đang dùng. Chọn model khác."

    return f"Gemini API call failed: {message}"


def _build_prompt(
    *,
    text: str,
    source: str,
    target: str,
    style: str,
    context: str | None,
    glossary: str | None,
    history: Sequence[Turn],
) -> str:
    parts: list[str] = [
        f"Translate from {source} to {target}.",
        _STYLE_GUIDANCE.get(style, _STYLE_GUIDANCE["casual"]),
    ]
    if context and context.strip():
        parts.append(
            "Situation / domain (use the terminology a professional in this "
            f"setting would use):\n{context.strip()}"
        )
    if glossary and glossary.strip():
        parts.append(
            "Glossary \u2014 these mappings are mandatory whenever the term appears, "
            "even if another wording sounds more natural:\n" + glossary.strip()
        )
    if history:
        rendered = "\n".join(
            f"- {turn.source_text.strip()} \u2192 {turn.target_text.strip()}"
            for turn in history
            if turn.source_text.strip() and turn.target_text.strip()
        )
        if rendered:
            parts.append(
                "Recent conversation (oldest first) \u2014 use it to resolve pronouns, "
                "omitted subjects and follow-up questions:\n" + rendered
            )
    parts.append(f"{source} input to translate:\n{text.strip()}")
    return "\n\n".join(parts)


_LABELS = (
    "translation",
    "translated",
    "korean",
    "vietnamese",
    "\ud55c\uad6d\uc5b4",
    "\ubc88\uc5ed",
    "b\u1ea3n d\u1ecbch",
    "d\u1ecbch",
)
_LABEL_RE = re.compile(
    rf"^\s*(?:{'|'.join(_LABELS)})\s*[:\uff1a]\s*",
    re.IGNORECASE,
)


def clean_translation(raw: str, *, source_text: str = "") -> str:
    """Strip the artefacts small models occasionally prepend to a translation.

    Flash-Lite sometimes echoes the source line before the translation, or
    wraps the answer in quotes / a ``Translation:`` label. Streaming means we
    cannot use a response schema to prevent it, so we clean it up here.
    """
    text = (raw or "").replace("\r", "").strip()
    if not text:
        return ""

    source = source_text.strip()
    lines = [line.strip() for line in text.split("\n")]
    lines = [line for line in lines if line]
    if source and len(lines) > 1 and lines[0] == source:
        lines = lines[1:]
    text = "\n".join(lines).strip()

    text = _LABEL_RE.sub("", text)
    for opening, closing in (('"', '"'), ("'", "'"), ("\u201c", "\u201d"), ("\u300c", "\u300d")):
        if len(text) > 1 and text.startswith(opening) and text.endswith(closing):
            text = text[1:-1].strip()
    return text.strip()
